### PR TITLE
feat: #13 convert project to be SSG based

### LINKED ISSUE #13: Phase 3 - Jamstack cutover
## Type of Change
- [x] New Feature Request
- [ ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
Coming out of #9 , tracking all the work specifically needed to go live with the new Jamstack rebuild.

## Details
1. [ ] CMS / content
1. [ ] Admin Page / Dashboard
1. [ ] Serverless APIs ?
1. [ ] Hybrid Architecture (discussion), pending on Greenwood I think
1. [ ] Go live checklist
1. [ ] Performance before / after benchmarks

### LINKED ISSUE #111: adopt SST for website deployments
Greenwood has an AWS adapter that can support SST based deployments.  Would be a better alternative than our hand-rolled deployment scripts
https://greenwoodjs.dev/guides/hosting/aws/

### PR DESCRIPTION
**Pull request by thescientist13**
## Related Issue
resolves #13 

## Summary of Changes
1. Refactor project to be SSG based, using `getStaticProps` / `getStaticParams`

## TODO
1. [x] Pages
    - ~~artists (landing)~~
    - ~~artist details~~
    - ~~albums (landing)~~
    - ~~album details~~
    - ~~contact~~
    - ~~events~~
    - ~~event details~~
    - ~~home page~~
1. [x] upstream the feature - https://github.com/ProjectEvergreen/greenwood/issues/1622
1. [x] unexpected output? -  https://github.com/AnalogStudiosRI/www.analogstudios.net/pull/112#issuecomment-4504021531
1. [x] posts list styles are breaking on `adoptedStyleSheets` usage 
1. [x] figure out issue with escaping JSON for artist bio / album title (fix in DB?)
1. [x] figure out why Quick Links event handling doesn't work
    - needs https://github.com/ProjectEvergreen/wcc/pull/272 ?
1. [x] figure out why Social Share component is not showing links (+ fix styles) - https://github.com/peterpeterparker/web-social-share/issues/65
    - FF does not support native sharing... :/ - https://github.com/mozilla/standards-positions/issues/27
1. [x] Greenwood upgrade types
1. [x] Greenwood static assets busted
1. [x] setup SST - #111 
    - [~~API requests not working~~](https://github.com/AnalogStudiosRI/www.analogstudios.net/pull/112#issuecomment-4870007140)
    - [events page is returning empty event details page](https://github.com/AnalogStudiosRI/www.analogstudios.net/pull/112#issuecomment-4870007140)
1. [x] make sure all name / title -> link encoding is working (e.g. check all links)
1. [x] clicking link on artist / album details leads to 404 page
1. [x] responsiveness / like for like check with production site
    - ~~social share styles~~
    - ~~album / artist details mobile~~
    - ~~long content overflows on details pages~~
    - ~~events images overflowing~~
1. [x] meta tags / SEO / page level `<title>` tags
1. [x] make scripts use `data-gwd-opt="static"` where possible
    - can posts list just be a static component? - no, it makes fetches
1. [x] unpatch patch-package / overrides - https://github.com/ProjectEvergreen/greenwood/pull/1675
1. [x] workflows
    - ~~oxfmt~~ - sticking with Prettier
    - ~~oxlint~~ (what about typescript eslint?) - keeping (ES|TS)Lint
    - husky / lint-staged
1. [x] refresh README (tech stack)

## Cutover Tasks
1. [ ] fork repo / copy issues / archive repo
1. [ ] hook up new domain name 
1. [ ] setup redirects from old site to new site
1. [ ] disconnect Netlify
1. [ ] clean up environment variables in GitHub Actions
1. [ ] backup v1 / merge v2 into main
1. [x] configure Preview environment for PRs

## Upstreams / Thoughts
1. [ ] WCC
    - ~~(inline) event handlers not supported / no event object callback~~ - https://github.com/ProjectEvergreen/wcc/pull/272
    - ~~shadow root detection~~ - https://github.com/ProjectEvergreen/wcc/pull/276
    - ~~types support~~ - https://github.com/ProjectEvergreen/wcc/issues/277
        - `tabindex` (buttons)
        - `<svg>` (social share component has TS error on SVG tag)
    - ~~svg types still broken~~ - https://github.com/ProjectEvergreen/wcc/pull/280
    - (nice to have) private members / methods don't work for event handlers - https://github.com/ProjectEvergreen/wcc/issues/279
    - (nice to have) import aliases don't work (this might not be solvable short term) - TODO upstream issue
1. [ ] Greenwood
    - ~~`GetStaticParams` types broken~~ - https://github.com/ProjectEvergreen/greenwood/pull/1698
    - ~~static pages are busted~~
    - tsx pages not working?
    - ~~content as data client w/ `getStaticParams`?~~ - see https://github.com/ProjectEvergreen/greenwood/discussions/1692
    - meta tags are not merging
    
## Fast Follows
1. [ ] https://github.com/AnalogStudiosRI/www.analogstudios.net/issues/113
1. [ ] upgrade TypeScript 6 / 7
1. [x] Next iteration (phase 3) - https://github.com/AnalogStudiosRI/www.analogstudios.net/discussions/37
    - caching API calls
    - effect?
    - what should be SSG vs SSR vs CSR + APIs?
      - should we move to markdown?
      - keep "real time" content as client side APIs?
    - should we just merge the API repo into this project?
1. [ ] remove bootstrap (Open Props) / font-awesome / refactor for more idiomatic CSS styles
1. [ ] analytics (server side?)
1. [ ] isormphic service endpoints
1. [ ] stylelint fixup prefers reduced motion
1. [ ] paginate (by year?) events fetching 
1. [ ] restore storybook
1. [ ] restore testing (Vitest)
1. [ ] get navigation links from content collection
1. [ ] track misc TODOs
1. [ ] refactor events calendar to use Temporal API
1. [ ] sitemap
1. [ ] centralize / share all calendar related constants
1. [ ] would be nice to have albums sub-pathed by artist; e.g. `/[artist]/album/[album-name]/`
1. [ ] filter SST config for SSR pages per - https://github.com/ProjectEvergreen/greenwood/blob/v0.34.0-alpha.9/packages/plugin-adapter-aws/src/index.js#L81
1. [ ] restore test cases + GitHub Actions (wtr or vitest? - probably vitest, since we'll also be using storybook)

### CODE REVIEW

**Comment by thescientist13** [comment]
An interesting observation, but page bundles are still being emitted for _src/pages/albums/index.ts_ and _src/pages/artists/index.ts_ pages.  Shouldn't these be HTML as well?  🤔 
Screenshot 2026-05-20 at 9 29 31 PM

I suppose it would make sense, since I don't have `prerender` enabled?  I should check that (and also on Netlify... though the build is currently failing...) and make sure that is coming out as HTML too.  (and also make sure those bundles aren't emitted)

---

Yeah, just needed to enable `prerender: true` 😅 

Screenshot 2026-05-28 at 10 00 20 AM

**Comment by thescientist13** [comment]
Even though we're not using any prerendering here, I think I've run into a possible ambiguous issue with Greenwood where in the social share component is getting SSR'd via WCC, even though all I want from the page is its HTML output, I don't actually want to SSR `<as-social-share></as-social-share>`.  In other words, why is WCC even running here at all?  🤔 
```
TypeError [Error]: Cannot read properties of undefined (reading 'call')
    at file:///Users/owenbuckley/Workspace/analogstudiosri/www.analogstudios.net/src/components/social-share/social-share.tsx:16:37
    at file:///Users/owenbuckley/Workspace/analogstudiosri/www.analogstudios.net/src/components/social-share/social-share.tsx:59:122
    at _optionalChain (file:///Users/owenbuckley/Workspace/analogstudiosri/www.analogstudios.net/src/components/social-share/social-share.tsx:16:15)
    at SocialShare.connectedCallback (file:///Users/owenbuckley/Workspace/analogstudiosri/www.analogstudios.net/src/components/social-share/social-share.tsx:59:5)
    at initializeCustomElement (file:///Users/owenbuckley/Workspace/analogstudiosri/www.analogstudios.net/node_modules/wc-compiler/src/wcc.js:200:27)
    at async renderComponentRoots (file:///Users/owenbuckley/Workspace/analogstudiosri/www.analogstudios.net/node_modules/wc-compiler/src/wcc.js:32:33)
    at async renderComponentRoots (file:///Users/owenbuckley/Workspace/analogstudiosri/www.analogstudios.net/node_modules/wc-compiler/src/wcc.js:64:7)
    at async renderComponentRoots (file:///Users/owenbuckley/Workspace/analogstudiosri/www.analogstudios.net/node_modules/wc-compiler/src/wcc.js:64:7)
    at async renderComponentRoots (file:///Users/owenbuckley/Workspace/analogstudiosri/www.analogstudios.net/node_modules/wc-compiler/src/wcc.js:64:7)
    at async renderComponentRoots (file:///Users/owenbuckley/Workspace/analogstudiosri/www.analogstudios.net/node_modules/wc-compiler/src/wcc.js:64:7)
```

```tsx
connectedCallback() {
  if (!this.shadowRoot) {
    this.attachShadow({ mode: 'open' });
  }
  
  // TODO: temp workaround for https://github.com/AnalogStudiosRI/www.analogstudios.net/pull/112#issuecomment-4564633209
  if(typeof window !== 'undefined') {
    this.render();
    defineCustomElement();

    this?.shadowRoot?.adoptedStyleSheets?.push(themeSheet, socialShareSheet);
    this?.shadowRoot?.querySelector('.wss')?.addEventListener('closed', () => {
      this?.toggleShowSocialShare();
    });
  }
}
```

> _maybe something to track as part of https://github.com/ProjectEvergreen/greenwood/issues/1249_

**Comment by thescientist13** [comment]
Noticing another defect with this implementation, that may be related to the ambiguous behavior [cited above](https://github.com/AnalogStudiosRI/www.analogstudios.net/pull/112#issuecomment-4564633209), but the event details page (_src/pages/events[title].ts_), which is a dynamic SSR page, is being emitted as HTML
Screenshot 2026-06-06 at 3 30 29 PM

File: src/components/card/card.tsx [hunk 1]
```diff
@@ -0,0 +1,89 @@
...
+// TODO: CSS Module Scripts do not work with SSR pages
+
+interface Details {
+  imagePath: string;
+  headingText: string;
+  bodyText: string;
+  imageAltText: string;
+  link: string;
+}
+
```
Comment (thescientist13) [inline src/components/card/card.tsx:13]: These should have a return type (e.g. Details)

**Review by thescientist13 — COMMENTED** [review]
After upgrade to v0.34.0-alpha.7, static pages are completely broken when running `npm run build && npm run serve` 😭 

Image
Image
Image

**Comment by thescientist13** [comment]
Seeing these type errors after the latest Greenwood upgrade

**Greenwood**
```sh
➜  www.analogstudios.net git:(v2) ✗ npm run lint

> www.analogstudios.net@2.0.0 lint
> eslint && ls-lint "./src/**/*.js" && stylelint "./src/**/*.css" && tsc

node_modules/@greenwood/cli/src/types/ssr.d.ts:40:34 - error TS7031: Binding element 'params' implicitly has an 'any' type.

40 export type GetStaticParams = ({ params }) => Promise<StaticParam>;
                                    ~~~~~~


Found 1 error in node_modules/@greenwood/cli/src/types/ssr.d.ts:40
```

**WCC**
```sh
node_modules/wc-compiler/src/jsx.d.ts:53:13 - error TS2320: Interface 'IntrinsicElements' cannot simultaneously extend types 'IntrinsicElementsFromDom' and 'IntrinsicElementsFromSVG'.
  Named property '"a"' of types 'IntrinsicElementsFromDom' and 'IntrinsicElementsFromSVG' are not identical.

53   interface IntrinsicElements extends IntrinsicElementsFromDom, IntrinsicElementsFromSVG {}
               ~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/wc-compiler/src/jsx.d.ts:53
```

**Comment by thescientist13** [comment]
The SST build is working now, but there are a couple of issues

### API Endpoints are 404
Screenshot 2026-07-02 at 4 00 47 PM

### Events page is showing empty details page
Screenshot 2026-07-02 at 4 00 26 PM
